version: "3.7"

services:
  database_ignite:
    image: postgres
    container_name: database_ignite
    restart: always
    ports:
     - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=ignite
      - POSTGRES_DB=rentx
    volumes:
      - pgdata:/data/postgres
    # network_mode: host
  app:
    build: .
    container_name: rentx
    ports: 
      - 3333:3333
      - 9229:9229
    volumes:
      - .:/usr/app
    links:
      - database_ignite
    depends_on:
      - database_ignite
    # network_mode: host
  
  # rentx_test:
  #   image: postgres
  #   container_name: rentx_test_db
  #   restart: always
  #   ports:
  #    - 5433:5432
  #   environment:
  #     - POSTGRES_USER=docker
  #     - POSTGRES_PASSWORD=ignite
  #     - POSTGRES_DB=rentx
  #   volumes:
  #     - pgdata:/data/postgres
    # network_mode: host

volumes:
  pgdata: 
    driver: local


# networks:
#   localignite:
#     name: host
#     external: true
# networks:
#  default:
#    external:
#     name: localignite